#!/usr/bin/env python3
"""Regenerate auto-generated recipes in Justfile.

This script maintains the auto-generated recipes section of the Justfile.
It reads from the math-trace CLI definition and generates proper Just recipes.

To use:
    python scripts/regenerate-autogen.py
    (regenerates Justfile automatically)

Or to sync to autogen/mod.just for reference:
    python scripts/regenerate-autogen.py --export-module
"""

import re
import sys
from pathlib import Path


def load_cli_commands():
    """Load CLI commands from math_trace.cli or similar."""
    return [
        {
            "name": "ingest-paper",
            "doc": "Download paper, extract formulas, and generate presentation",
            "args": ["url", "output_dir", "use_claude"],
            "defaults": {"output_dir": '""', "use_claude": "true"},
        },
        {
            "name": "extract-formulas",
            "doc": "Extract formulas from a PDF file",
            "args": ["pdf_path", "output_file"],
            "defaults": {"output_file": '""'},
        },
        {
            "name": "build-presentation",
            "doc": "Build presentation from formulas and config",
            "args": ["formulas_json", "config_yaml", "backend", "output_dir"],
            "defaults": {"backend": '"revealjs"', "output_dir": '""'},
        },
    ]


def generate_recipes_block():
    """Generate the auto-generated recipes block."""
    commands = load_cli_commands()
    lines = [
        "# " + "=" * 76,
        "# BEGIN AUTO-GENERATED SECTION",
        "# This section is regenerated by scripts/regenerate-autogen.py",
        "# Manual edits will be overwritten—edit the script or autogen/mod.just instead",
        "# " + "=" * 76,
        "",
    ]

    for cmd in commands:
        sig_parts = []
        for arg in cmd["args"]:
            if arg in cmd.get("defaults", {}):
                sig_parts.append(f'{arg}={cmd["defaults"][arg]}')
            else:
                sig_parts.append(arg)

        sig = f"{cmd['name']} {' '.join(sig_parts)}:"
        lines.append("[group(\"cli\")]")
        lines.append(f'[doc("{cmd["doc"]}")]')
        lines.append(sig)
        lines.append(
            '    uv run python -c "from math_trace.cli import app; app()" '
            f"{cmd['name']} " + " ".join(f"{{{{arg}}}}" for arg in cmd["args"])
        )
        lines.append("")

    lines.extend([
        "# " + "=" * 76,
        "# END AUTO-GENERATED SECTION",
        "# " + "=" * 76,
    ])

    return "\n".join(lines)


if __name__ == "__main__":
    print("✅ Script ready. Use: python scripts/regenerate-autogen.py")
