#!/bin/bash
# Precommit hook: Regenerate autogenerated files from Typer CLI apps
#
# Usage:
#   bash scripts/regenerate-autogen.sh [--check-only]
#
# Behavior:
#   - Detects if autogenerated files are out of sync with source
#   - Regenerates if needed (when run by precommit)
#   - Aborts commit and instructs user to review + recommit
#   - Returns 0 if up to date, 1 if regenerated, 2 if errors

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
PYTHON="${PYTHON:-python3}"

# Navigate to project root
cd "$PROJECT_DIR"

# Run the Python regeneration script
$PYTHON "$SCRIPT_DIR/regenerate-autogen.py" "$@"
EXIT_CODE=$?

case $EXIT_CODE in
    0)
        # All files up to date
        echo ""
        echo "✅ Autogenerated files are in sync"
        exit 0
        ;;
    1)
        # Files were regenerated
        echo ""
        echo "⚠️  Autogenerated files were out of sync and have been regenerated"
        echo ""
        echo "📋 To proceed, please:"
        echo "   1. Review the changes:"
        echo "      git diff"
        echo "   2. Stage the generated files:"
        echo "      git add $(git status --short | grep -E "^ M|^\?\?" | awk '{print $2}' | xargs)"
        echo "   3. Commit again:"
        echo "      git commit -m \"<your message>\""
        echo ""
        exit 1
        ;;
    2)
        # Check-only: files would need regeneration
        echo ""
        echo "❌ Autogenerated files are out of sync with source"
        echo ""
        echo "Run to regenerate:"
        echo "   just regenerate"
        echo ""
        exit 1
        ;;
    *)
        # Error occurred
        echo ""
        echo "❌ Error during autogeneration"
        exit 2
        ;;
esac
